<a href="https://colab.research.google.com/github/dipaksavitre-don/asssiment-25/blob/main/assignment25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""Q1. (Manual Hyperparameter Tuning – KNN)
Load the Iris dataset.
Split into train and test sets (test_size=0.33, random_state=42).
Create a KNN model and manually try different values of n_neighbors (e.g., 3, 5, 7, 11, 13, 15).
For each value, train the model and print the test score.
Write which value gave the highest accuracy.
"""
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()

pd.DataFrame(data=iris.data,columns=iris.feature_names)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:


# Convert target integers into species names
species = pd.Categorical.from_codes(iris.target, iris.target_names)

# Create DataFrame with features + species
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = species

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [ ]:
# spliting into trainin and testing
from sklearn.model_selection import train_test_split
x = iris.data
y = iris.target

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33, random_state=42,shuffle=True)

In [ ]:
# creating the knn model and trying  to it on different values
from sklearn.neighbors import KNeighborsClassifier

scores = {}
values = [3, 5, 7, 11, 13, 15]

for i in values:
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(x_train,y_train)
    score = model.score(x_test,y_test)
    scores[i]=score
    print(f"for N_neighbors:{i} accuracy is:{score}")

for N_neighbors:3 accuracy is:0.98
for N_neighbors:5 accuracy is:0.98
for N_neighbors:7 accuracy is:0.98
for N_neighbors:11 accuracy is:1.0
for N_neighbors:13 accuracy is:1.0
for N_neighbors:15 accuracy is:1.0

on the iris dataset the values of n_neighbors = 11,13 and 15 gives the highest accuracy it suggest that having the large number of the neighbors classification help our model to perform better

In [ ]:
"""Q2. (Manual Hyperparameter Tuning – SVM)
Using the same train-test split from Q1:
Create an SVM model and manually try different combinations of C (1, 10, 20) and kernel (linear, rbf).
Train each combination and print the test accuracy.
Identify the best combination of hyperparameters.
"""

from sklearn.svm import SVC

c = [1, 10, 20]

kernal = ['linear','rbf']

for  i in kernal:
    for j in c:

        model = SVC(C=j,kernel=i)
        model.fit(x_train,y_train)
        score = model.score(x_test,y_test)
        print(f"For kernal :{i} and C :{j} score = {score}")

For kernal :linear and C :1 score = 1.0
For kernal :linear and C :10 score = 1.0
For kernal :linear and C :20 score = 0.98
For kernal :rbf and C :1 score = 1.0
For kernal :rbf and C :10 score = 0.98
For kernal :rbf and C :20 score = 1.0

the best combination of the hyperparameters are c = 1 and kernal = linear , c = 10 and kernal = linear and c = 1 kernal = rbf and c= 20 and kernal = rbf

In [ ]:
"""Q3. (Grid Search CV)
Apply GridSearchCV on an SVM model:
Create a DataFrame of cv_results_ and display param_C, param_kernel, and
mean_test_score.
Print the best parameters and best score."""

from sklearn.model_selection import GridSearchCV

grid = {'C':[1,10,20],'kernel':['linear','rbf']}

model2 = SVC()

grid_search = GridSearchCV(model2,grid,cv=5)

grid_search.fit(x_train,y_train)

cv_results = pd.DataFrame(grid_search.cv_results_)
best_params = grid_search.best_params_
best_score = grid_search.best_score_

In [ ]:
cv_results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1       linear             0.95
1        1          rbf             0.93
2       10       linear             0.93
3       10          rbf             0.94
4       20       linear             0.93
5       20          rbf             0.95

In [ ]:
best_params,best_score

({'C': 1, 'kernel': 'linear'}, np.float64(0.95))

In [ ]:
"""Q4. (Randomized Search CV)
Apply RandomizedSearchCV on the same SVM model:
Use the same parameter grid as Q3.
Set n_iter=5 and cv=5.
Fit the model.

Display the results DataFrame with important columns.
Compare the best parameters and score with Grid Search results from Q3."""

# applyinh RandomizedSearchCV on the same SVM model

from sklearn.model_selection import RandomizedSearchCV

random_grid = {'C':[1,10,20],'kernel':['linear','rbf']}

model3 = SVC()

random_search = RandomizedSearchCV(model3,random_grid,n_iter=5,cv=5)

random_search.fit(x_train,y_train)

results = pd.DataFrame(random_search.cv_results_)
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       20       linear             0.93
1       10          rbf             0.94
2        1          rbf             0.93
3       20          rbf             0.95
4       10       linear             0.93

In [ ]:
random_search.best_params_ , random_search.best_score_

({'kernel': 'rbf', 'C': 20}, np.float64(0.95))

In [ ]:
"""Q5. (Bagging – Random Forest)
Train a Random Forest Classifier on the Iris dataset:
Use n_estimators=100 and random_state=42.
Perform train-test split (test_size=0.2, stratify=y).
Train the model and calculate accuracy on the test set.
Print the accuracy score."""

from sklearn.ensemble import RandomForestClassifier

# traing the model on existing train and test data
rf = RandomForestClassifier(n_estimators=100,random_state=42)
rf.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [ ]:
accuracy = rf.score(x_test,y_test)

In [ ]:
# training the model on new train and test data with test_size=0.2, stratify=y
x_train2,x_test2,y_train2,y_test2 = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

rf2 = RandomForestClassifier(n_estimators=100,random_state=42)
rf2.fit(x_train2,y_train2)

RandomForestClassifier(random_state=42)

In [ ]:
accuracy2 = rf2.score(x_test2,y_test2)

In [ ]:
print(f"Accuracy on test set with test_size=0.33: {accuracy}")
print(f"Accuracy on test set with test_size=0.2: {accuracy2}")

Accuracy on test set with test_size=0.33: 0.98
Accuracy on test set with test_size=0.2: 0.9

In [ ]:
"""Q6. (Boosting – AdaBoost & Gradient Boosting)
Train the following models:
AdaBoostClassifier (n_estimators=100, random_state=42)
GradientBoostingClassifier (n_estimators=100, learning_rate=0.1,
random_state=42)
Calculate and print the accuracy of both models on the test set."""

from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

ada_model = AdaBoostClassifier(n_estimators=100,random_state=42)
gb_model = GradientBoostingClassifier(n_estimators=100,learning_rate=0.1,random_state=42)

accuracy_ada = ada_model.fit(x_train,y_train).score(x_test,y_test)
accuracy_gb = gb_model.fit(x_train,y_train).score(x_test,y_test)
print(f"Accuracy of AdaBoost model on test set: {accuracy_ada}")
print(f"Accuracy of Gradient Boosting model on test set: {accuracy_gb}")

Accuracy of AdaBoost model on test set: 0.94
Accuracy of Gradient Boosting model on test set: 0.98

In [ ]:
"""Q7. (Boosting – XGBoost)
Train an XGBClassifier with:
n_estimators=100
learning_rate=0.1
max_depth=3
random_state=42
Calculate and print the test accuracy."""

from xgboost import XGBClassifier

xgb_model = XGBClassifier(n_estimators=100,learning_rate=0.1,max_depth=3,random_state=42)
accuracy_xgb = xgb_model.fit(x_train,y_train).score(x_test,y_test)
print(f"Accuracy of xgboost model on iris dataset is:{accuracy_xgb}")

Accuracy of xgboost model on iris dataset is:0.98

In [ ]:
"""Q8. (Hyperparameter Tuning on Random Forest)
Apply GridSearchCV on Random Forest Classifier:
Parameter grid:
n_estimators: [50, 100, 150]
max_depth: [3, 5, 7]
Use cv=5.
Find and print the best parameters and best score."""

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {'n_estimators': [50, 100, 150],'max_depth': [3, 5, 7]}
random_forest = RandomForestClassifier(random_state=42)

grid_search_rf = GridSearchCV(random_forest,param_grid,cv=5)
grid_search_rf.fit(x_train,y_train)
print(f"Best Parmeters for random forest:{grid_search_rf.best_params_}")
print(f"Best Score for random forest:{grid_search_rf.best_score_}")

Best Parmeters for random forest:{'max_depth': 3, 'n_estimators': 50}
Best Score for random forest:0.9400000000000001

In [ ]:
"""Q9. (Complete Model Comparison)
On the Iris dataset (or any other classification dataset):
Train and evaluate the following models:
SVM (with best parameters from GridSearch/RandomSearch)
Random Forest
AdaBoost
Gradient Boosting
XGBoost
Create a comparison table of all models with their accuracy scores and write
which model performed the best."""

# identifying the best parameters for SVM from previous grid search

c = [1, 10, 20]

kernal = ['linear','rbf']

svm_model = SVC()
grid = GridSearchCV(svm_model, param_grid={'C': c, 'kernel': kernal}, cv=5)

mdl = grid.fit(x_train,y_train)
parameter_svm = mdl.best_params_
score_svm = mdl.best_score_
accuracy_svm = mdl.score(x_test,y_test)

In [ ]:
prams_rf = {'n_estimators': [50, 100, 150], 'max_depth': [3, 5, 7]}
rf = RandomForestClassifier()
grid_rf = GridSearchCV(rf, param_grid=prams_rf, cv=5)
mdl2 = grid_rf.fit(x_train,y_train)
accuracy_rf = mdl2.score(x_test,y_test)
prameter_rf = mdl2.best_params_
score_rf = mdl2.best_score_

In [ ]:
prams_ada = {'n_estimators': [50, 100, 150], 'learning_rate': [0.01, 0.1, 1]}
ada_model = AdaBoostClassifier()
grid_ada = GridSearchCV(ada_model, param_grid=prams_ada, cv=5)
mdl3 = grid_ada.fit(x_train,y_train)
accuracy_ada = mdl3.score(x_test,y_test)
prams_ada = mdl3.best_params_
score_ada = mdl3.best_score_

In [ ]:
grid_gb = {'n_estimators': [50, 100, 150], 'learning_rate': [0.01, 0.1, 1]}
gb_model = GradientBoostingClassifier()
grid_gb = GridSearchCV(gb_model,param_grid=grid_gb,cv=5)
mdl4  = grid_gb.fit(x_train,y_train)
accuracy_gb = mdl4.score(x_test,y_test)
prams_gb = mdl4.best_params_
score_gb = mdl4.best_score_

In [ ]:
prams_xgb = {'n_estimators': [50, 100, 150], 'learning_rate': [0.01, 0.1, 1], 'max_depth':[3,5,7]}
xgb_model = XGBClassifier()
grid_xgb = GridSearchCV(xgb_model,param_grid=prams_xgb,cv=5)
mdl5 = grid_xgb.fit(x_train,y_train)
accuracy_xgb = mdl5.score(x_test,y_test)
score_xgb = mdl5.best_score_
prams_xgb = mdl5.best_params_

In [ ]:
models = {
    'SVM': {'accuracy': accuracy_svm, 'best_params': parameter_svm, 'best_score': score_svm},
    'Random Forest': {'accuracy': accuracy_rf, 'best_params': prameter_rf, 'best_score': score_rf},
    'AdaBoost': {'accuracy': accuracy_ada, 'best_params': prams_ada, 'best_score': score_ada},
    'Gradient Boosting': {'accuracy': accuracy_gb, 'best_params': prams_gb, 'best_score': score_gb},
    'XGBoost': {'accuracy': accuracy_xgb, 'best_params': prams_xgb, 'best_score': score_xgb}
}

# creating a comparison table of all models with their accuracy scores
comparison_table = pd.DataFrame.from_dict(models)

In [ ]:
comparison_table.T

,accuracy,best_params,best_score
SVM,1.0,"{'C': 1, 'kernel': 'linear'}",0.95
Random Forest,1.0,"{'max_depth': 3, 'n_estimators': 100}",0.94
AdaBoost,0.98,"{'learning_rate': 0.1, 'n_estimators': 100}",0.94
Gradient Boosting,1.0,"{'learning_rate': 0.01, 'n_estimators': 100}",0.92
XGBoost,1.0,"{'learning_rate': 0.01, 'max_depth': 3, 'n_est...",0.92